# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "/#posts"
  weight = 20

## [[main]]
##   name = "Gallery"  # Title of the link.
##   url = "#gallery"  # Widget Page folder name.
##   weight = 25  # Position of the link in the navigation bar.

[[main]]
  name = "Projects"
  url = "/#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "/#publications"
  weight = 40

[[main]]
  name = "Teaching"
  url = "/#teaching"
  weight = 50 

[[main]]
  name = "I’m Learning"
  url = "/learning/"
  weight = 55
  
[[main]]
  name = "Slides"
  url = "/#slides"
  weight = 60 
  
[[main]]
  name = "Contact"
  url = "/#contact"
  weight = 70
  
[[main]]
  name = "Gallery"
  url = "/gallery"
  weight = 80
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
