---
title: 臨牀實驗的樣本量計算問題 Sample Size in Clinical Trial
author: ''
date: '2017-10-29'
slug: sample-size-in-clinical-trial
categories:
  - study abroad
  - statistics
tags:
  - learning notes
  - Medical Statistics
  - LSHTM
  - London
  - Clinical Trial
summary: "臨牀實驗的樣本量計算問題"
---


### 背景

計劃臨牀實驗的時候，爲了避免偏倚和帶有偏見的結論，應當將注意力放在

1. 如何將實驗對象隨機分配 (randomisation)
2. 設計對照組 (control group)
3. 合適（且必須）的貫徹盲法 (blinding)

另外一個同樣重要的問題是--**“我到底需要多少樣本?”**

一項臨牀實驗，應該提供足夠的證據來證明新藥物（新治療方法）是否有效，是否安全。影響一個實驗設計的樣本量的因素可能有如下幾種：

1. **統計學方案。**
    <br> 從統計學上可以推算出，需要多少樣本來獲得一個堅實可信的證據來證明藥物的實際有效性。
2. 經濟上的因素。
    <br> 然而實際上可能還有經濟上，時間上，人力物力資源上的現實因素，會制約到底一個實驗能夠收集到多少樣本量。
3. 倫理道德上的因素。
    <br> 許多臨牀實驗還必須受制於醫學倫理因素。在倫理上一個實驗到底可以維持多久。或者說，要考慮當實驗中一些受試者的結果不理想，或者是有副作用的時候，我們何時該及時停止該實驗？
4. 實驗本身的可信度。
    <br> 如果一個臨牀實驗的規模在設計上就很小，可能它本身的可信度就很低。

這裏我們只考慮沒有其他任何因素的影響下，**1. 統計學方案**上該如何計算準確的所需樣本量的大小。

比較下列兩個同樣比較了溶栓酶和安慰劑在預防心肌梗塞患者死亡的臨牀實驗：

治療組         | 溶栓酶     | 安慰劑                      | p-value
---------------|------------|-----------------------------|----------
1st Australian | n=264      | n=253                       |
死亡人數       | 26 (9.8%)  | 32 (12.6%)                  | p = 0.32
評價           | Risk ratio | 0.78 (95% CI: 0.48 to 1.27) |
ISIS-2         | n=8592     | n=8595                      |
死亡人數       | 791 (9.2%) | 1029 (12.0%)                 | p < 0.001
評價           | Risk ratio | 0.77 (95% CI: 0.70 to 0.84) |


這兩個臨牀實驗獲得的治療效果 (treatment effect)，在數字的百分比上幾乎十分接近。然而由於樣本兩巨大的差距，可以看到第一個實驗的信賴區間十分的大，使得實驗結果是無意義的。而第二個大樣本的實驗結果就告訴我們，溶栓酶的治療效果是有效降低了心肌梗死患者死亡概率（降低了23%）。第一個實驗收集了近500個病例，卻仍然不能提供確實有效的證據證明溶栓酶的治療效果（提供了強的關聯結果，卻是極弱的證據。strong correlation, but weak evidence) 。


### 決定所需樣本量大小的統計學因素

(1) 實驗主要結果的測量/比較方法是什麼？ What is the principal outcome measure of the trial?
<br> 一項臨牀實驗的主要結果，應該是切合該實驗的主要目的的。並且應當能夠客觀評價。(如死亡率的改善，治癒率的提高等等)

(2) 實驗數據準備分析的方案是什麼？ How will the data be analysed to detect a treatment difference?
<br> 實驗結果獲得的數據是連續型的 (血壓，血糖值，BMI)？還是分類的離散變量 (死亡的發生與否，疾病的治癒與否)？統計學上認爲的，治療結果提示有意義的差別時的概率。通常定爲 5%。(p < 0.05)

(3) 對照組的試驗期望結果是怎樣的？ What results are expected in the control group?
<br> 當然我們不可能事先預知實驗對照組可能出現的結果。此處只討論我們的預期結果。大多數情況下，我們可以從已經進行過的類似臨牀試驗報告中獲得，或者是從非臨牀干預型研究（觀察型研究）報告中獲得對照組的期望結果。

(4) 如果實驗藥物在治療上確實有差異，當這個差異最小爲多少時希望能從設計的實驗中被檢測到？ How small a treatment difference, if it exists, is important to detect?
<br> 這一條恐怕是每個臨牀實驗在設計階段最重要，最敏感也是最難做出決定的。如果我們已知這個藥物療效和對照相比差別很大，那麼樣本量不用很大，就足以提供值得信賴的證據。不過臨牀上常常會認爲療效差距不必**非常的**顯著，但是在臨牀意義上也是十分重要的。
<br> 常常在這個問題上會引起衆多討論，因爲醫生和患者可能認爲任何一點差異都是有臨牀意義的。但是如果我們想檢測出較小的差距，會需要非常巨大的樣本量，這將會是十分不切合實際的。**What needs to be decided upon is the smallest clinically relevant difference that would be important to detect if it were true.**

(5) 在上面第 4 條被決定了以後，還要確定的是我們需要多大的把握來相信這個被檢測出來的療效差別？ With what degree of certainty is needed to be able to detect the treatment difference in 4?
<br> 在實際臨牀實驗中，結論是從觀察數據中得來的，而不是從我們預想的那個“未知的實驗效果”。觀察獲得的療效差別，可能比預想的大（有效），也很可能比預想的小（無效）。設計較好的臨牀實驗應該有足夠機率觀察到有意義的療效差別，即使觀察得到的結果不如預期的大。當然要增加我們觀察到有意義的療效差別，最簡單的辦法是增加樣本量。這個條件的含義是，當療效真差別真實存在，我們要有足夠大的把握把它通過實驗觀察到。

### 第一類和第二類錯誤 Type I and type II errors

下面羅列一下我們在進行實驗設計時要用到的概念和相應的標記，注意雖然我們無法知道真正的人羣裏真實參數 (parameter) 的大小，但是我們需要用一些估計 (estimator) 來代替：

- $p_1=$ the **observed percentage** in those on standard treatment <br> 意爲施行標準治療法時觀察到的（治癒/有效）百分比
- $p_2=$ the **observed percentage** in those on "new" treatment <br> 意爲施行“新療法”時觀察到的（治癒/有效）的百分比

$\Rightarrow p_1-p_2=$ **observed treatment effect** <br> 意爲可以觀察到的治療效果。

- $\pi_1=$ the **anticipated percentage** in those on standard treatment <br> 意爲施行標準治療法時，我們預期的（治癒/有效）百分比
- $\pi_2=$ the **anticipated percentage** in those on "new" treatment <br> 意爲施行“新療法”時，我們預期的（治療/有效）百分比

$\Rightarrow \pi_1-\pi_2=$ is the true difference which has been decided it is important to detect <br> 意爲上面第 4 條中我們設定好的希望通過實驗證實的真實的療效差別。

其餘的數學標記包括：

- $\alpha=$ 有意義的療效差異，在統計學上的水平 (概率水平，通常設定爲 0.05 or 5%)
- $1-\beta=$ Degree of certainty that a true difference of $\pi_1 - \pi_2$ would be detected. <br> 效能, power。意爲有多大的把握能通過實驗檢測出療效差別。（通常將目標值設定爲 $1-\beta=90\%$）


|                          |       無**真實差別**       | $\pi_1-\pi$ **真實差別**存在 |
|--------------------------|:--------------------------:|:----------------------------:|
| **觀察到**不存在有意義差別 |         $1-\alpha$         |  $\beta$ <br> Type II error  |
| **觀察到**存在有意義差別   | $\alpha$ <br> Type I error |       $1-\beta$ <br> Power        |

- **Type I error:** A type I error is when a treatment difference is claimed based on a statistically significant observed result when in truth no such difference exists, i.e. a false positive result.
- **Type II error:** A type II error is when in truth there exists a difference of $\pi_1-\pi_2$ but the observed results fail to reach statistical significance, i.e. a false negative result.

Alternative ways of describing $\alpha$ and $\beta$ are as follows:
- $\alpha$ is the risk of a type I error;
- $\beta$ is the risk of a type II error. $1-\beta$ is termed statistical power.
