---
title: 「統計解析のための線形代数」復習筆記 27
author: ''
date: '2017-08-11'
slug: homogeneouse-linear-equations
categories:
  - statistics
tags:
  - basic mathematics
  - linear algebra
  - Medical Statistics
summary: "第5章　行列式 determinant P94-96 同次連立一次方程式"
---

$$X=\left(
\begin{array}{c}
x_{1} & x_{12} & \cdots & x_{1n}\\
x_{21} & x_{22} & \cdots & x_{2n}\\
\vdots & \vdots & \cdots & \vdots \\
x_{n1}  & x_{n2} & \cdots & x_{nn}
\end{array}
\right), \underline{a}=\left(
\begin{array}{c}
a_1 \\
a_2 \\
\vdots \\
a_n
\end{array}
\right), \underline{0}=\left(
\begin{array}{c}
\underline{0}\\
\underline{0}\\
\vdots\\
\underline{0}\\
\end{array}
\right)$$

用上述來表達的同次連立一次方程式 (system of homogeneouse linear equations)：

$$X\underline{a}=\underline{0}$$

即：
$$\begin{align}
\left\{
\begin{array}{ll}
x_{11}a_1+x_{12}a_2+\cdots+x_{1n}a_n  = 0\\
x_{21}a_1+x_{22}a_2+\cdots+x_{2n}a_n  = 0\\
\cdots\\
x_{n1}a_1+x_{n2}a_2+\cdots+x_{nn}a_n  = 0\\
\end{array}
\right.
\end{align}$$

這樣的方程式與之前的不同，等號右邊全部都是 $0$.
如果係數矩陣的行列式 $|X|$

$$|X|=\begin{vmatrix}
x_{1} & x_{12} & \cdots & x_{1n}\\
x_{21} & x_{22} & \cdots & x_{2n}\\
\vdots & \vdots & \cdots & \vdots \\
x_{n1}  & x_{n2} & \cdots & x_{nn}
\end{vmatrix}\neq0$$

那麽這個連立方程式的解，我們通過[克萊姆法則](https://winterwang.github.io/post/cramers-formula/)公式知道有且僅有 $\underline{a}=\underline{0}$， 即 $a_1=a_2=\cdots=a_n=0$ (自明解, trivial solution)

此外，如果此連立方程組有非自明解 ($\underline{a}\neq0$) 那麽相應的， $|X|=0$。多元變量分析時我們多關心的是非自明解。

<span class="diff_alert">重點記住：<br>$\underline{a}\neq0$ 時， $|X|=0$； <br>$\underline{a}=0$ 時, $|X|\neq0$</span>


(1) 方程組 $\begin{align}
\left\{
\begin{array}{ll}
a_1+2a_2  = 0\\
2a_1+a_2  = 0\\
\end{array}
\right.
\end{align}$ 的係數矩陣 $\left(
\begin{array}{c}
1 & 2 \\
2 & 1 \\
\end{array}
\right)$ 的行列式 $\begin{vmatrix}
1 & 2\\
2 & 1\\
\end{vmatrix}=-3\neq0$ 所以此同次連立一次方程組的解有且僅有 $a_1=a_2=0$ (自明解)。

(2) 方程組  $\begin{align}
\left\{
\begin{array}{ll}
-a_1+2a_2  = 0 \;\;\;\;\;\;\;(1)\\
2a_1-4a_2  = 0 \;\;\;\;\;\;\;\;(2)\\
\end{array}
\right.
\end{align}$ <br>的係數行列式  $\begin{vmatrix}
-1 & 2\\
2 & -4\\
\end{vmatrix}=0$，因此除了自明解 $a_1=a_2=0$ 之外，還有非自明解。由於 $(2)=-2\times(1)$，$(1),(2)$ 實質上是一個相同的方程式。 按照[前述方法](https://winterwang.github.io/post/2017-02-12-t/)，我們設定 $a_2=s$ ($s$ 為非零任意實數)，則 $a_1=2s$。所以可以將這個方程組的非自明解寫作：
$$\underline{a}=s\left(
\begin{array}{c}
2\\
1
\end{array}
\right), s 為非零任意實數。$$

$\star 自明解和非自明解同時表述時可以寫作: \underline{a}=s\left(
\begin{array}{c}
2\\
1
\end{array}
\right),\\ s 為任意實數。$


(3) 方程組 $\begin{align}
\left\{
\begin{array}{ll}
(1-\lambda)a_1+2a_2  = 0 \;\;\;\;\;\;\;(1)\\
4a_1+(3-\lambda)a_2  = 0 \;\;\;\;\;\;\;(2)\\
\end{array}
\right.
\end{align}$ 有非自明解的條件為：
$$\begin{align}
\begin{vmatrix}
1-\lambda & 2\\
4 & 3-\lambda
\end{vmatrix} & = (1-\lambda)(3-\lambda)-4\times2 \\
& = 3-4\lambda+\lambda^2-8 \\
& = \lambda^2-4\lambda-5 \\
& = (\lambda+1)(\lambda-5) \\
& = 0
\end{align}\\
\therefore \lambda=-1, 5$$
<br>

  -  $\lambda=-1$ 時，代入 $(1),(2)$ 得<br>  $\begin{align}
  \left\{
  \begin{array}{ll}
  2a_1+2a_2  = 0 \;\;\;\;\;\;\;(1)\\
  4a_1+4a_2  = 0 \;\;\;\;\;\;\;(2)\\
  \end{array}
  \right.
  \end{align}$ 為實質上只有一個方程 $a_1+a_2=0$ 的方程組。令 $a_2=s$， 則 $a_1=-s$。因此此時方程組的非自明解為 $\underline{a}=s\left(
  \begin{array}{c}
  1\\
  2
  \end{array}
  \right)$ ($s$ 為 $0$ 意外的任意實數)。
  - $\lambda=5$ 時，同理可得， $\underline{a}=t\left(
  \begin{array}{c}
  1\\
  2
  \end{array}
  \right)$ ($t$ 為 $0$ 意外的任意實數)。

(4) 方程組 $(\zeta)\begin{align}
\left\{
\begin{array}{r}
(5-\lambda)a_1+2a_2-4a_3  = 0\\
-3a_1-\lambda a_2+4a_3  = 0\\
6a_1+6a_2-(1+\lambda)a_3  = 0\\
\end{array}
\right.
\end{align}$ 擁有非自明解的條件為：
$$\begin{vmatrix}
5-\lambda & 2        & -4 \\
-3        & -\lambda & 4  \\
6         & 6        & -(1+\lambda)
\end{vmatrix}=0$$

按照以前我們做過的[練習](https://winterwang.github.io/post/2017-03-15/)將行列式按照 $\lambda$ 展開：
$$-\lambda^3+4\lambda^2-\lambda-6=\\
-(\lambda+1)(\lambda-2)(\lambda-3)=0\\
\therefore \lambda=-1,2,3$$

 - $\lambda = -1$ 時， $(\zeta)$ 變為：$\begin{align}
 \left\{
 \begin{array}{r}
 6a_1+2a_2-4a_3  = 0\\
 -3a_1+ a_2+4a_3  = 0\\
 6a_1+6a_2  = 0\\
 \end{array}
 \right.
 \end{align}$，此時的非自明解為 $\underline{a}=s\left(
 \begin{array}{c}
 1\\
 -1\\
 1
 \end{array}
 \right)$ ($s$ 為 $0$ 以外的任意實數)
 - $\lambda = 2$ 時， $(\zeta)$ 變為：$\begin{align}
 \left\{
 \begin{array}{r}
 3a_1+2a_2-4a_3  = 0\\
 -3a_1-2a_2+4a_3  = 0\\
 6a_1+6a_2-3a_3 = 0\\
 \end{array}
 \right.
 \end{align}$，此時的非自明解為 $\underline{a}=t\left(
 \begin{array}{c}
 6\\
 -5\\
 2
 \end{array}
 \right)$ ($t$ 為 $0$ 以外的任意實數)
 - $\lambda = 3$ 時， $(\zeta)$ 變為：$\begin{align}
 \left\{
 \begin{array}{r}
 2a_1+2a_2-4a_3  = 0\\
 -3a_1-3a_2+4a_3  = 0\\
 6a_1+6a_2-4a_3  = 0\\
 \end{array}
 \right.
 \end{align}$，此時的非自明解為 $\underline{a}=u\left(
 \begin{array}{c}
 1\\
 -1\\
 0
 \end{array}
 \right)$ ($u$ 為 $0$ 以外的任意實數)

$3, 4$ 與後面的固有值問題關係深刻。
