---
title: 「統計解析のための線形代数」復習筆記9
author: Chaochen Wang
date: '2017-02-18'
categories: [statistics]
tags:
  - learning notes
  - basic mathematics
  - linear algebra
summary: "第3章　向量 vector P34-38"
---


## 特殊向量

#### 零向量 (zero vector, null vector)

1. 全部的成分均爲$0$的向量，我們稱之爲**零向量(zero vector, null vector)**, 寫作： $\underline{0}$
2. 注意與**標量(scalar)** $0$ 相區分。
3. 如果想要加注零向量的維度，我們可以在右下角加上 $n$：$\underline{0}_n$ ，意爲 $n$ 維度的零向量。
4. 不是零向量的向量又被叫做，**非零向量(non-zero vector, non-null vector)**。

例如： 列向量：$\underline{0}_3=\left(
\begin{array}{c}
0\\
0\\
0\\
\end{array}
\right)$， 行向量：$\underline{0}_3^t=(0,0,0)$


#### $1$ 向量 (vector with all elements 1)

1. 當一個向量的全部成分都是數字 $1$，我們稱這個向量爲 $1$ 向量。 $\underline{1}$
2. 這裏也需要注意與**標量** $1$ 相區分。
3. 如果想要加注$1$向量的維度，我們可以在右下角加上 $n$：$\underline{1}_n$ ，意爲 $n$ 維度的$1$向量。

例如：列向量：$\underline{1}_4=\left(
\begin{array}{c}
1\\
1\\
1\\
1
\end{array}
\right)$， 行向量：$\underline{1}_4^t=(1,1,1,1)$


#### 第 $i$ 基本向量

```{theorem, name="fundamental vector"}
$n$ 維度的向量，假如它的第 $i$ 個成分是自然數 $1$，其他的成分全部都是 $0$， 我們稱這樣的向量爲**第** $\textbf{i}$ **基本向量 (fundamental vector)**。寫作 $\underline{\smash{e}}_i$。
```

* 平時我們較少用到一個單獨的基本向量。大多情況下我們用的是由 $n$ 個單獨向量組成的一組向量。這個類型的向量與坐標軸的關系緊密。

例如：維度爲4的第 $1\sim4$ 基本向量：$\underline{e}_1=\left(
\begin{array}{c}
1\\
0\\
0\\
0
\end{array}
\right), \;
\underline{e}_2=\left(
\begin{array}{c}
0\\
1\\
0\\
0
\end{array}
\right), \;
\underline{e}_3=\left(
\begin{array}{c}
0\\
0\\
1\\
0
\end{array}
\right), \;
\underline{e}_4=\left(
\begin{array}{c}
0\\
0\\
0\\
1
\end{array}
\right)$



#### 單位向量 (unit vector)

```{theorem, name="unit vector"}
求向量的各個成分平方和的正平方根，當結果爲 $1$ 時，這個向量被稱作**單位向量(unit vector)**。寫作： $\underline{e}$。
```

例如： 因爲 $\sqrt{(\frac{2}{3})^2+(-\frac{1}{3})^2+(\frac{2}{3})^2}=1$，所以我們稱向量 $\underline{e}=\left(
\begin{array}{c}
\frac{2}{3}\\
-\frac{1}{3}\\
\frac{2}{3}\\
\end{array}
\right)$ 爲**單位向量**。另外，$(\frac{1}{\sqrt{2}},-\frac{1}{\sqrt{2}},0)^t, \; (\frac{2}{\sqrt{6}},\frac{1}{\sqrt{6}},-\frac{1}{\sqrt{6}})^t$，以及前一項的**第 $i$ 基本向量**，都是單位向量。


## 向量的計算，與相等

#### 向量的和與差

```{theorem, name="vectorplus"}
類型(type)/成分，維度相同的向量之間的加減運算定義爲：相對應的成分之間的和或差。
```

例如：

1.  $\underline{a}=\left(
\begin{array}{c}
a_1\\
a_2\\
\vdots\\
a_n
\end{array}
\right), \; \underline{b}=\left(
\begin{array}{c}
b_1\\
b_2\\
\vdots\\
b_n
\end{array}
\right)$，則有： <br>
$\underline{a}\pm\underline{b}=\left(
\begin{array}{c}
a_1\\
a_2\\
\vdots\\
a_n
\end{array}
\right)\pm\left(
\begin{array}{c}
b_1\\
b_2\\
\vdots\\
b_n
\end{array}
\right)=\left(
\begin{array}{c}
a_1 \pm b_1\\
a_2 \pm b_2\\
\vdots\\
a_n \pm b_n
\end{array}
\right)$ **複号同順**

2. $\underline{a}= (a_1,a_2,\cdots,a_n), \; \underline{b} = (b_1,b_2,\cdots,b_n)$，則有： <br>
$\underline{a}\pm\underline{b}=(a_1,a_2,\cdots,a_n)\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;+(b_1,b_2,\cdots,b_n)\\
\;\;\;\;\;\;\;\;\;\;=(a_1 \pm b_1, a_2 \pm b_2, \cdots, a_n \pm b_n)$ <br>**複号同順**


### 練習

1. $\underline{a}=\left(
\begin{array}{c}
6\\
7\\
8\\
\end{array}
\right),$ $\underline{b}=\left(
\begin{array}{c}
1\\
3\\
5\\
\end{array}
\right)$ 時，$\underline{a}+\underline{b} =\left(
\begin{array}{c}
6+1\\
7+3\\
8+5\\
\end{array}
\right)=\left(
\begin{array}{c}
7\\
10\\
13\\
\end{array}
\right)$ <br>
$\underline{a}-\underline{b}=\left(
\begin{array}{c}
6-1\\
7-3\\
8-5\\
\end{array}
\right)=\left(
\begin{array}{c}
5\\
4\\
3\\
\end{array}
\right)$

2. $\underline{c}=(6,0,9), \underline{d}=(7,-3,2)$ 時，<br>
$\underline{c}+\underline{d}=(6+7,0-3,9+2)=(13,-3,11)$ <br>
$\underline{c}-\underline{d}=(6-7,0-(-3),9-2)=(-1,3,7)$

#### 向量的標量乘法(scalar multiplication)

```{theorem, name="scalar multiplication"}
向量 $\underline{a}$ 的所有成分同時乘以標量 $(k)$ 以後的向量，我們稱爲 $\underline{a}$ 的標量 $k$ 倍。寫作： $k\underline{a}$。特別地，當 $k=1$ 時，$1\underline{a}=\underline{a}$，$k=-1$ 時，$(-1)\underline{a}=-\underline{a}$。另外 $k=0$ 時，$0\underline{a}=\underline{0}$。注意此時$\underline{0}$是與$\underline{a}$同維度的零向量。不可寫作標量的 $0$。
$$k\underline{a}=k\left(
\begin{array}{c}
a_1\\
a_2\\
\vdots\\
a_n
\end{array}
\right)=\left(
\begin{array}{c}
ka_1\\
ka_2\\
\vdots\\
ka_n
\end{array}
\right), \\k\underline{a}=k(a_1,a_2,\cdots,a_n)=(ka_1,ka_2,\cdots,ka_n)$$
```

### 練習

1. $k=5, l=\frac{1}{9}, \underline{a}=\left(
\begin{array}{c}
3\\
2\\
-7\\
\end{array}
\right)$ 時，<br>
$k\underline{a}=5\left(
\begin{array}{c}
3\\
2\\
-7\\
\end{array}
\right)=\left(
\begin{array}{c}
5\times3\\
5\times2\\
5\times(-7)\\
\end{array}
\right)=\left(
\begin{array}{c}
15\\
10\\
-35\\
\end{array}
\right)$, <br>
$l\underline{a}=\frac{1}{9}\left(
\begin{array}{c}
3\\
2\\
-7\\
\end{array}
\right)=\left(
\begin{array}{c}
\frac{1}{9}\times3\\
\frac{1}{9}\times2\\
\frac{1}{9}\times(-7)\\
\end{array}
\right)=\left(
\begin{array}{c}
\frac{1}{3}\\
\frac{2}{9}\\
-\frac{7}{9}\\
\end{array}
\right)$

2. $\underline{a}=\left(
\begin{array}{c}
3\\
-2\\
4\\
\end{array}
\right), \underline{b}=\left(
\begin{array}{c}
1\\
1\\
-3\\
\end{array}
\right), \underline{c}=\left(
\begin{array}{c}
0\\
5\\
2\\
\end{array}
\right)$ 時，<br>
$2\underline{a}-\underline{b}+3\underline{c}=\left(
\begin{array}{c}
2\times3\\
2\times(-2)\\
2\times4\\
\end{array}
\right)-\left(
\begin{array}{c}
1\\
1\\
-3\\
\end{array}
\right)\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;+\left(
\begin{array}{c}
3\times0\\
3\times5\\
3\times2\\
\end{array}
\right)=\left(
\begin{array}{c}
6-1+0\\
-4-1+15\\
8-(-3)+6\\
\end{array}
\right)=\left(
\begin{array}{c}
5\\
10\\
17\\
\end{array}
\right)$


#### 向量相等 equal

```{theorem, name="vectors equal"}
類型(type)/成分，維度相同的向量 $\underline{a}, \underline{b}$，其對應成分完全一致，我們就稱 $\underline{a}=\underline{b}$，此時有 $\underline{a}-\underline{b}=\underline{0}$ **零向量**。
```

### 練習：

1. $\underline{a}=\left(
\begin{array}{c}
a_1\\
a_2\\
a_3\\
\end{array}
\right), \underline{b}=\left(
\begin{array}{c}
b_1\\
b_2\\
b_3\\
\end{array}
\right)$ 如果相等，那麼 $\underline{a}=\underline{b}$，<br>即：$\begin{align}
\left\{
\begin{array}{ll}
a_1 = b_1 \\
a_2 = b_2 \\
a_3 = b_3
\end{array}
\right.
\end{align}$ 等價於：$\underline{a}-\underline{b}=0$，或者<br>
$\begin{align}
\left\{
\begin{array}{ll}
a_1 - b_1 =0\\
a_2 - b_2 =0\\
a_3 - b_3 =0
\end{array}
\right.
\end{align}$

2. 向量等式：$\left(
\begin{array}{c}
a_{11}x_1+a_{12}x_2+a_{13}x_3\\
a_{21}x_1+a_{22}x_2+a_{23}x_3\\
a_{31}x_1+a_{32}x_2+a_{33}x_3\\
\end{array}
\right)=\left(
\begin{array}{c}
b_1\\
b_2\\
b_3\\
\end{array}
\right)$ 等價於三個等式的連立方程：<br>
$\begin{align}
\left\{
\begin{array}{ll}
a_{11}x_1+a_{12}x_2+a_{13}x_3= b_1\\
a_{21}x_1+a_{22}x_2+a_{23}x_3= b_2\\
a_{31}x_1+a_{32}x_2+a_{33}x_3= b_3
\end{array}
\right.
\end{align}$

3. 求滿足 $5\left(
\begin{array}{c}
a_1\\
a_2\\
a_3\\
\end{array}
\right)+\left(
\begin{array}{c}
2\\
5\\
-1\\
\end{array}
\right)=\left(
\begin{array}{c}
12\\
25\\
29\\
\end{array}
\right)$ 的向量 $\underline{a}=\left(
\begin{array}{c}
a_1\\
a_2\\
a_3\\
\end{array}
\right)$。<br>
解：$5\left(
\begin{array}{c}
a_1\\
a_2\\
a_3\\
\end{array}
\right)=\left(
\begin{array}{c}
12\\
25\\
29\\
\end{array}
\right)-\left(
\begin{array}{c}
2\\
5\\
-1\\
\end{array}
\right)=\left(
\begin{array}{c}
10\\
20\\
30\\
\end{array}
\right)$<br>
因此，$\underline{a}=\left(
\begin{array}{c}
a_1\\
a_2\\
a_3\\
\end{array}
\right)=\left(
\begin{array}{c}
2\\
4\\
6\\
\end{array}
\right)$
