---
title: 「統計解析のための線形代数」復習筆記11
author: Chaochen Wang
date: '2017-02-21'
categories: [statistics]
tags:
  - learning notes
  - basic mathematics
  - linear algebra
summary: "第4章　矩陣 matrix P46-52"
---



## 矩陣的定義

```{theorem, name="matrix"}
將$m\times n$ 個數 $a_{ij} (i=1,2,\cdots,m; j=1,2,\cdots,n)$, 寫成縱 $m$ 行， 橫 $n$ 列的長方形或者正方形，左右用圓括號或者方括號包含在內。我們稱之爲 $m\times n$ **矩陣(matrix)**，或者 $(m, n)$ 矩陣。 $m\times n$ 或者 $(m,n)$ 被稱爲是這個矩陣的類型。我們常用大寫字母來標記一個矩陣，如下面的矩陣我們標記爲 $A$。 如果要特別明示矩陣的類型，可以寫作 $\mathop{A}_{m\times n}, \mathop{A}_{(m, n)}, \; A(m\times n)$。兩個矩陣如果行數相等，列數也相等，我們稱他們爲類型相同的矩陣。構成矩陣的一個個數 $a_{11},a_{12},\cdots,a_{mn}$ 被叫做矩陣的成分(component, element, entry)。

第$i$行，第$j$列交叉的地方的成分，$a_{ij}$ 被叫做 $(i,j)$ 成分。矩陣有時候也會寫成 $A=(a_{ij})$
```

$\left(
\begin{array}{c}
a_{11} & a_{12} &  \cdots & a_{1j} & \cdots & a_{1n}\\
a_{21} & a_{22} &  \cdots & a_{2j} & \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots & \ddots & \vdots\\
a_{i1} & a_{i2} &  \cdots & a_{ij} & \cdots & a_{in}\\
\vdots & \vdots &  \ddots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} &  \cdots & a_{mj} & \cdots & a_{mn}\\
\end{array}
\right), \\ \left[
\begin{array}{c}
a_{11} & a_{12} &  \cdots & a_{1j} & \cdots & a_{1n}\\
a_{21} & a_{22} &  \cdots & a_{2j} & \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots & \ddots & \vdots\\
a_{i1} & a_{i2} &  \cdots & a_{ij} & \cdots & a_{in}\\
\vdots & \vdots &  \ddots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} &  \cdots & a_{mj} & \cdots & a_{mn}\\
\end{array}
\right]$


* 矩陣  $\mathop{A}_{m\times n}$ 可以被看做是：<br>
  以第$1$行爲成分的行向量 $(a_{11},a_{12},\cdots,a_{1n})=\underline{b}_1^t$；<br>
  以第$2$行爲成分的行向量 $(a_{21},a_{22},\cdots,a_{2n})=\underline{b}_2^t$；<br>
  $\vdots$<br>
  以第 $m$ 行爲成分的行向量 $(a_{m1},a_{m2},\cdots,a_{mn})=\underline{b}_m^t$；<br>
  爲成分組成的列向量：<br>
  $\left(
  \begin{array}{c}
  \underline{b}_1^t\\
  \underline{b}_2^t\\
  \vdots\\
  \underline{b}_m^t\\
  \end{array}
  \right)$

* 類似的，矩陣  $\mathop{A}_{m\times n}$ 可以被看做是：<br>
  以第$1$列爲成分的列向量： $\left(
  \begin{array}{c}
  a_{11}\\
  a_{21}\\
  \vdots\\
  a_{m1}\\
  \end{array}
  \right)=\underline{c}_1$ <br>
  以第$2$列爲成分的列向量：$\left(
  \begin{array}{c}
  a_{12}\\
  a_{22}\\
  \vdots\\
  a_{m2}\\
  \end{array}
  \right)=\underline{c}_2$ <br>
  $\vdots$<br>
  以第$n$列爲成分的列向量：$\left(
  \begin{array}{c}
  a_{1n}\\
  a_{2n}\\
  \vdots\\
  a_{mn}\\
  \end{array}
  \right)=\underline{c}_n$ <br>
  爲成分組成的行向量：$(\underline{c}_1,\underline{c}_2,\cdots,\underline{c}_n)$


## 矩陣的運算，和零矩陣
### 矩陣的和與差

```{theorem, name="matrix plus or minus"}
類型(type)相同的矩陣之間的加減法運算，被定義爲各個對應成分的加減法結果作成分的矩陣。
```

對於$A=\left(
\begin{array}{c}
a_{11} & a_{12} &  \cdots & a_{1n}\\
a_{21} & a_{22} &  \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} &  \cdots & a_{mn}\\
\end{array}
\right),\\
B=\left(
\begin{array}{c}
b_{11} & b_{12} &  \cdots & b_{1n}\\
b_{21} & b_{22} &  \cdots & b_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
b_{m1} & b_{m2} &  \cdots & b_{mn}\\
\end{array}
\right)$ <br>
有：$A\pm B=\left(
\begin{array}{c}
a_{11} & a_{12} &  \cdots & a_{1n}\\
a_{21} & a_{22} &  \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} &  \cdots & a_{mn}\\
\end{array}
\right)\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\pm \left(
\begin{array}{c}
b_{11} & b_{12} &  \cdots & b_{1n}\\
b_{21} & b_{22} &  \cdots & b_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
b_{m1} & b_{m2} &  \cdots & b_{mn}\\
\end{array}
\right)\\
\;\;\;\;\;\;\;\;\;\;=\left(
\begin{array}{c}
a_{11}\pm b_{11} & a_{12}\pm b_{12} &  \cdots & a_{1n}\pm b_{1n}\\
a_{21}\pm b_{21} & a_{22}\pm b_{22} &  \cdots & a_{2n}\pm b_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1}\pm b_{m1} & a_{m2}\pm b_{m2} &  \cdots & a_{mn}\pm b_{mn}\\
\end{array}
\right)(復号同順)$


1. $A=\left(
     \begin{array}{c}
     9 & 3 &  1\\
     -2 & 5 &  8\\
     \end{array}
     \right)， B=\left(
     \begin{array}{c}
     4 & 2 &  1\\
     3 & -3 & 5\\
     \end{array}
     \right)$ 那麼<br>
     $A+B = \left(
          \begin{array}{c}
          9+4 & 3+2 &  1+1\\
          -2+3 & 5+(-3) &  8+5\\
          \end{array}
          \right)=\left(
               \begin{array}{c}
               13 & 5 &  2\\
               1 & 2 &  13\\
               \end{array}
               \right)$

2. 用1.中的矩陣運算：<br>
   $A-B=\left(
        \begin{array}{c}
        9-4 & 3-2 &  1-1\\
        -2-3 & 5-(-3) &  8-5\\
        \end{array}
        \right)=\left(
             \begin{array}{c}
             5 & 1 &  0\\
             -5 & 8 &  3\\
             \end{array}
             \right)$

### 矩陣的相等
```{theorem, name="matrix equal"}
類型相同的兩個矩陣 $A,B$，如果他們對應的所有成分，一一相等，我們說這兩個矩陣是相等的。即：$A=B$。
```
對於$A=\left(
\begin{array}{c}
a_{11} & a_{12} &  \cdots & a_{1n}\\
a_{21} & a_{22} &  \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} &  \cdots & a_{mn}\\
\end{array}
\right),\\
B=\left(
\begin{array}{c}
b_{11} & b_{12} &  \cdots & b_{1n}\\
b_{21} & b_{22} &  \cdots & b_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
b_{m1} & b_{m2} &  \cdots & b_{mn}\\
\end{array}
\right)$<br>
如果有：<br>
$a_{11}=b_{11},a_{12}=b_{12},\cdots,a_{mn}=b_{mn}$<br>
那麼 $A=B$。

### 零矩陣
```{theorem, name="zero matrix"}
所有的成分均爲數字 $0$ 的 $m\times n$ 矩陣，<br>
(共有　$m\times n$ 個零。)<br>
$\left(
\begin{array}{c}
0 & 0 &  \cdots & 0\\
0 & 0 &  \cdots & 0\\
\vdots & \vdots &  \ddots & \vdots\\
0 & 0 &  \cdots & 0\\
\end{array}
\right)$<br>
被稱爲**零矩陣(zero matrix, null matrix)**。寫作：$\large 0, \mathop{\large 0}_{m\times n}, \mathop{\large 0}_{(m,n)}$。要注意與標量的 $0$ 區分。
```

### 矩陣的標量倍數運算
```{theorem, name="scalar times"}
矩陣 $A$ 的所有的成分，均乘以一個標量 $k$，獲得新的矩陣的過程被稱爲矩陣的標量倍數運算。 寫作 $kA$。
```

對於 $A=\left(
\begin{array}{c}
a_{11} & a_{12} &  \cdots & a_{1n}\\
a_{21} & a_{22} &  \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} &  \cdots & a_{mn}\\
\end{array}
\right)$，<br>
有：$kA = k\left(
\begin{array}{c}
a_{11} & a_{12} &  \cdots & a_{1n}\\
a_{21} & a_{22} &  \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} &  \cdots & a_{mn}\\
\end{array}
\right)\\
=\left(
\begin{array}{c}
ka_{11} & ka_{12} &  \cdots & ka_{1n}\\
ka_{21} & ka_{22} &  \cdots & ka_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
ka_{m1} & ka_{m2} &  \cdots & ka_{mn}\\
\end{array}
\right)$

特別的，當 $k=-1$ 時， $(-1)A=-A$，$k=0$ 時，$0A=\Large 0$。注意 $\Large 0$ 是與 $A$ 類型相同的零矩陣，而非標量 $0$。


1. 對 $A=\left(
\begin{array}{c}
a_{11} & a_{12} &  a_{13}\\
a_{21} & a_{22} &  a_{23}\\
a_{31} & a_{32} &  a_{33}\\
\end{array}
\right)$， <br>
$kA=\left(
\begin{array}{c}
ka_{11} & ka_{12} &  ka_{13}\\
ka_{21} & ka_{22} &  ka_{23}\\
ka_{31} & ka_{32} &  ka_{33}\\
\end{array}
\right)$

2. 對 $B=\left(
\begin{array}{c}
1 & -2 &  3\\
-4 & 5 &  -6\\
\end{array}
\right)$，<br>
$7B=\left(
\begin{array}{c}
7\times1 & 7\times(-2) &  7\times3\\
7\times(-4) & 7\times5 &  7\times(-6)\\
\end{array}
\right)\\
\;\;\;\;=\left(
\begin{array}{c}
7 & -14 & 21\\
-28 & 35 &  -42\\
\end{array}
\right)$<br>
$-B=\left(
\begin{array}{c}
-1 & 2 &  -3\\
4 & -5 &  6\\
\end{array}
\right)$；<br>
$0B=\left(
\begin{array}{c}
0 & 0 &  0\\
0 & 0 &  0\\
\end{array}
\right)=\mathop{\large 0}_{2\times3}$
