---
title: 「統計解析のための線形代数」復習筆記4
author: Chaochen Wang
date: '2017-02-12'
categories: [statistics]
tags:
  - learning notes
  - basic mathematics
  - linear algebra
summary: "第1章　数学の基礎 P15-17"
---


## 連立方程式 (simultaneous equations)

連立方程式，將與第六章談的特徵值問題(固有値問題)有緊密聯系，此處我們一起觀察幾種不同的組合：


1. 解同次連立1次方程式 $\left\{ \begin{array}{ll}
           (1)\;a_1+2a_2+3a_3 = 0 \\
           (2)\;2a_1+4a_2+5a_3 = 0 \;\\
           (3)\;3a_1+5a_2+6a_3 = 0 \\
        \end{array} \right.$ <br>
  由 $2\times(1)-(2)$ 可得 $a_3=0$ 。 代入 $(1),(2),(3)$ 式後，$(3)-(2)$ 可得 $a_1=-a_2$ 。 代入 $(1)$ 式可得 $a_2=0$ 。 再代入 $(4)$ 式可知 $a_1=0$ 。最終可得 $a_1=a_2=a_3=0$ <br>
  其實上述問題不解自明 (trivial solution)。 那麼同次1次連立方程式 (homogeneous system) 除了自明解之外，還有別的解嗎? 我們再看下面一例。

2. 解 $\left\{ \begin{array}{ll}
           (1)\;4a_1+3a_2+6a_3 = 0 \\
           (2)\;2a_1+a_2+4a_3 = 0 \;\\
           (3)\;a_1+a_2+a_3 = 0 \\
        \end{array} \right.$ <br>
    上述方程表面上看有三個式子，實際上由於 $(3)=\left\{(1)-(2)\right\}\div2$ 只有2個有意義的方程式。如此這般，有3個未知數，卻只有兩個連立方程組，是無法求解的。如果將三個未知數中的一個例如 $a_3$ 視爲常數(定数) (寫作：$s$ ) 即： <br>$(4)\;a_3=s$ <br>
    整理方程組得到新的連立方程 $\left\{ \begin{array}{ll}
               (1^\prime)\;4a_1+3a_2 = -6s \\
               (2^\prime)\;2a_1+a_2 = -4s \;\\
               \end{array} \right.$ <br>
    由 $(1^\prime)-2\times(2^\prime)$ 可得 $a_2=2s$ 。代入 $(2^\prime)$ 可得 $a_1=-3s$。因此我們得到 $a_1=-3s,a_2=2s,a_3=s$ 且 $s$ 爲任意常數，故此連立方程組的解有無數組。當且僅當 $s=0$ 時方程組有自明解， $s\neq0$ 時此連立方程組的解爲非自明解 (non-trivial solution)。如果將其他未知數視爲常數(定数)時，求得的解會有變化嗎？<br>
    若視 $a_2=s$ 求解連立方程的解時，我們會獲得 $a_1=-\frac{3}{2}s, a_2=s, a_3=-\frac{1}{2}s$。若視 $a_1=s$ 時，計算可得 $a_1=s, a_2=-\frac{2}{3}s,a_3=-\frac{1}{3}s$。<br>
    由此可見，非自明解表面看去各不相同，但是都滿足了 $a_1:a_2:a_3=-3:2:1$ 的本質條件。

3. 解 $\left\{ \begin{array}{ll}
           (1)\;4a_1+3a_2+6a_3 = 0 \\
           (2)\;2a_1+a_2+4a_3 = 0 \;\\
           (3)\;a_1^2+a_2^2+a_3^2 = 0 \\
        \end{array} \right.$ <br>
   上述方程組其實是將例題2.中的方程 $(3)$ 替換成了2次方程。<br>
   $3\times(2)-(1)$ 可得 $a_1=-3a_3$ <br>
   $(1)-2\times(2)$ 可得 $a_2=2a_3$ <br>
   以上代入 $(3)$ 可得， $a_3 = \pm \frac{1}{\sqrt{14}}$。<br>
   總結一下：　$a_1=\mp \frac{3}{\sqrt{14}}, a_2=\pm \frac{2}{\sqrt{14}}, a_3=\pm\frac{1}{\sqrt{14}}$ (複号同順 double-sign corresponds)

4. 解 $a_1+2a_2-3a_3=0$ <br>
  上面的方程只有一個，並不是連立方程組，將其中兩個未知數視爲常數時就變成了只有一個未知數的方程。例如視，$a_2=s, a_3=t$ 代入上述方程則可以得到: $a_1=-2s+3t$，因此，此方程的解爲： $a_1=-2s+3t, a_2=s, a_3=t$，$s,t$ 爲任意常數，有無數組解。

#### 練習: 解下列連立方程組

1. $\left\{ \begin{array}{ll}
           (1)\;2a_1-3a_2 = 0 \\
           (2)\;-4a_1+6a_2 = 0 \;\\
        \end{array} \right.$

2. $\left\{ \begin{array}{ll}
           (1)\;2a_1-3a_2 = 0 \\
           (2)\;-4a_1+6a_2 = 0 \;\\
           (3)\;a_1^2+a_2^2 = 0 \\
        \end{array} \right.$ <br>

#### 解
1. $\because$ $(2)=-2\times(1)$ 實質上方程組僅有一個方程。<br>
   $\therefore a_1=\frac{3}{2}s, a_2=s$

2. 只需要求解例題1 中符合方程 $(3)$ 的解即可。 <br>
   $\therefore a_1=\pm\frac{3}{\sqrt{13}}, a_2=\pm\frac{2}{\sqrt{13}}$ (複号同順 double-sign corresponds)
