---
title: 「統計解析のための線形代数」復習筆記19
author: Chaochen Wang
date: '2017-04-02'
categories: [statistics]
tags:
  - learning notes
  - basic mathematics
  - linear algebra
summary: "第5章　行列式 determinant P80"
---

## 行列式的性質
具體的行列式的值，可以通過以下介紹的行列式性質，儘量簡潔地求解。本節也是爲了簡易示範，僅僅使用3次行列式作例子。4次以上的行列式性質依然相同，依此類推即可。

1. 轉置矩陣的行列式，與轉置前的行列式一致。即：$|A^t|=|A|$。 <br>
   $|A|=\begin{vmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
   \end{vmatrix}$
2. 任意一列（或者任意一行）若乘以 $\lambda$ 倍，那麼這個矩陣的行列式結果也將是乘以 $\lambda$ 倍。<br>
$|A|=\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
\lambda a_{21} &\lambda  a_{22} & \lambda a_{23}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}\\
\;\;\;\;=|A|=\lambda \begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}$<br>
$|A|=\begin{vmatrix}
a_{11} & a_{12} & \lambda a_{13}\\
a_{21} & a_{22} & \lambda a_{23}\\
a_{31} & a_{32} & \lambda a_{33}\\
\end{vmatrix}\\
\;\;\;\;=|A|=\lambda \begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}$
3. 任意一列（或者任意一行）的各成分乘以 $\lambda$ 倍，與其他任意一列（或者任意一行）的各成分進行加運算（或者減運算）獲得的矩陣的行列式與原矩陣的行列式相同。<br>
$\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21}\pm \lambda a_{11} & a_{22}\pm \lambda a_{12} & a_{23}\pm \lambda a_{13}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}，\\ \begin{vmatrix}
a_{11} & a_{12}\pm \lambda a_{11} & a_{13}\\
a_{21} & a_{22}\pm \lambda a_{21} & a_{23}\\
a_{31} & a_{32}\pm \lambda a_{31} & a_{33}\\
\end{vmatrix},$ <br>
$\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} \pm \frac{a_{11}}{\lambda} & a_{22}\pm \frac{a_{12}}{\lambda} & a_{23}\pm \frac{a_{13}}{\lambda}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}, \\
\begin{vmatrix}
a_{11} & a_{12}\pm \frac{a_{11}}{\lambda}  & a_{13}\\
a_{21} & a_{22}\pm \frac{a_{21}}{\lambda}  & a_{23}\\
a_{31} & a_{32}\pm \frac{a_{31}}{\lambda}  & a_{33}\\
\end{vmatrix}$<br>
上述行列式與行列式 $\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}$ 結果相同。

4. 符合下列條件時，行列式的值爲 $0$
    * 任意一行（或者列）的全部成分均爲 $0$ 時。
    * 矩陣中若有兩行（或者兩列）的對應成分全部相同時。
    * 矩陣中若有兩行（或者兩列）的對應成分均成一定比例時。<br>
   $\begin{vmatrix}
   a_{11} & a_{12} & a_{13}\\
   a_{21} & a_{22} & a_{23}\\
   0 & 0 & 0\\
   \end{vmatrix}=0\\
   \begin{vmatrix}
   a & b & c\\
   a & b & c\\
   d & e & f\\
   \end{vmatrix}=0\\
   \begin{vmatrix}
   a & b & c\\
   ka & kb & kc\\
   d & e & f\\
   \end{vmatrix}=0$<br>
   由於上面的後兩條成立，所以當矩陣中任意兩列（或者兩行）的對應成分幾乎相等，或者比值無限接近時，行列式的值也可以說就接近爲 $0$。此性質與多重線性迴歸的多重共線性有直接關係。

5. 一個矩陣中其中兩列（或者兩行）的成分交換以後獲得的矩陣，其行列式值爲原矩陣的行列式的值的相反數。（即符號相反）<br>
$\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}=-\begin{vmatrix}
a_{21} & a_{22} & a_{23}\\
a_{11} & a_{12} & a_{13}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}$ （第一行和第二行對調成分）
6. 對角矩陣，上三角矩陣，下三角矩陣的行列式的值，等於對角成分的積<br>
$\begin{vmatrix}
a_{11} & 0 & 0\\
0 & a_{22} & 0\\
0 & 0 & a_{33}\\
\end{vmatrix}=a_{11}a_{22}a_{33},\\
\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
0 & a_{22} & a_{23}\\
0 & 0 & a_{33}\\
\end{vmatrix}=a_{11}a_{22}a_{33},\\
\begin{vmatrix}
a_{11} & 0 & 0\\
a_{21} & a_{22} & 0\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}=a_{11}a_{22}a_{33}$
7. 矩陣中如果有任意一行（或列），衹有一個成分為非零成分，可以將該矩陣的行列式降次：<br>
$\begin{vmatrix}
a_{11} & 0 & 0\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\\
\end{vmatrix}=a_{11}(-1)^{1+1}\begin{vmatrix}
a_{22} & a_{23} \\
a_{32} & a_{33}
\end{vmatrix}$ <br>
<br>
$\begin{vmatrix}
a_{11} & a_{12} & 0\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & 0\\
\end{vmatrix}=a_{23}(-1)^{1+1}\begin{vmatrix}
a_{11} & a_{12} \\
a_{31} & a_{32}
\end{vmatrix}$

8. $A, B$ 同時都是正方形矩陣時，$|AB|=|A|·|B|$。

----
**證明** $A=\left(\begin{array}{c}
0 & 4 & 2\\
-1 & 3 & 7\\
6 & 5 & 9\\
 \end{array}\right)$，$B=\left(\begin{array}{c}
2 & 3 & 4\\
-2 & 7 & 1\\
4 & 6 & 0\\
 \end{array}\right)$ 時， $|AB|=|A|·|B|$ 成立
---

### 解
 $\because AB=\left(\begin{array}{c}
 0 & 40 & 4\\
 20 & 60 & -1\\
 38 & 107 & 29\\
 \end{array}\right)$ <br>
 $\therefore |AB|=\begin{vmatrix}
 0 & 40 & 4\\
 20 & 60 & -1\\
 38 & 107 & 29\\
 \end{vmatrix}$<br>
 <span class="diff_alert">利用性質3： 第2列 - 第3列 $\times$ 10 作新的第2列</span><br>
$=\begin{vmatrix}
0 & 0 & 4\\
20 & 70 & -1\\
38 & -183 & 29\\
\end{vmatrix}$<br>
 <span class="diff_alert">利用性質7： 第一行衹有第三個元素非零，可以降次。</span><br>
 $=4(-1)^{1+3}\begin{vmatrix}
 20 & 70 \\
 38 & -183\end{vmatrix}$ <br>
 <span class="diff_alert">利用性質2: 第一行所有元素除以10, 將 10 提前。</span><br>
 $=4\times10\begin{vmatrix}
 2 & 7 \\
 38 & -183\end{vmatrix}\\
 =40(-366-266)\\=-25280$<br>
<br>
 $|A|=\begin{vmatrix}
 0 & 4 & 2\\
 -1 & 3 & 7\\
 6 & 5 & 9\\
 \end{vmatrix}$ <br>
 <span class="diff_alert">利用性質3: 第2列 - 第3列 $\times$ 2 作爲新的第二列元素</span><br>
$=\begin{vmatrix}
0 & 0 & 2\\
-1 & -11 & 7\\
6 & -13 & 9\\
\end{vmatrix}$<br>
<span class="diff_alert">利用性質7: 第一行衹有第三個元素非零，降次。</span><br>
$=2(-1)^{1+3}\begin{vmatrix}
-1 & -11 \\
6 & -13\end{vmatrix}\\=2(13+66)=158$ <br>

$|B|=\begin{vmatrix}
2 & 3 & 4\\
-2 & 7 & 1\\
4 & 6 & 0\\
\end{vmatrix}$  <br>
<span class="diff_alert">利用性質3: 第1行 $+$ 第2行作新的第1行； 第3行 - 第1行 $\times$ 2 作新的第三行</span><br>
$=\begin{vmatrix}
0 & 10 & 5\\
-2 & 7 & 1\\
0 & 0 & -8\\
\end{vmatrix}$<br>
<span class="diff_alert">利用性質7: 第三行衹有第三個元素非零，降次。</span><br>
$=-8(-1)^{3+3}\begin{vmatrix}
0 & 10 \\
-2 & 7\end{vmatrix}\\=-8\times20=-160$

### 綜上可得
$|A|·|B|=158\times(-160)=-25280$
