---
title: 「統計解析のための線形代数」復習筆記16
author: Chaochen Wang
date: '2017-03-11'
categories: [statistics]
tags:
  - learning notes
  - basic mathematics
  - linear algebra
summary: "第4章　矩陣 matrix P68-69"
---

## 二次型(形式)

對於 $\underline{x}=\left(
\begin{array}{c}
x_{1}\\
x_{2}\\
\vdots\\
x_{n}
\end{array}
\right), A=\left(
\begin{array}{c}
a_{11}& a_{12} & \cdots & a_{1n}\\
a_{21}& a_{22} & \cdots & a_{2n}\\
\vdots& \vdots & \vdots & \vdots\\
a_{n1}& a_{n2} & \cdots & a_{nn}
\end{array}
\right)$ 那麼：<br>
$\underline{x}^tA\underline{x}=\sum\limits_{i=1}^n\sum\limits_{j=1}^na_{ij}x_ix_j\\
\;\;\;\;\;\;\;\;\:\:=\sum\limits_{i=1}^na_{ii}x_i^2+\mathop{\sum\limits^n\sum\limits^n}_{i \neq j}a_{ij}x_ix_j\\
\;\;\;\;\;\;\;\;\:\:=\sum\limits_{i=1}^na_{ii}x_i^2+\mathop{\sum\limits^n\sum\limits^n}_{i\ <\ j}(a_{ij}+a_{ji})x_ix_j$<br>
被稱爲 $\underline{x}$ 的同次2次式。又被叫做關於 $x_1,x_2,\cdots,x_n$ 的**2次型(quadratic form)**。特別的，當 $A$ 爲對稱矩陣時的2次型：$\underline{x}^tA\underline{x}=\sum\limits_{i=1}^na_{ii}x_i^2+2\mathop{\sum\limits^n\sum\limits^n}_{i\ <\ j}a_{ij}x_ix_j$ 在多元變量分析中十分重要。

1. $x=\left(
\begin{array}{}
x_1\\
x_2
\end{array}
\right),\ A=\left(
\begin{array}{}
a_{11} & a_{12}\\
a_{12} & a_{22}
\end{array}
\right)$, 那麼： <br>
$\underline{x}^tA\underline{x}=a_{11}x_1^2+a_{22}x_2^2+2a_{12}x_1x_2$

2. $x=\left(
\begin{array}{}
x_1\\
x_2\\
x_3
\end{array}
\right),\ A=\left(
\begin{array}{}
a_{11} & a_{12} & a_{13}\\
a_{12} & a_{22} & a_{23}\\
a_{13} & a_{23} & a_{33}
\end{array}
\right)$，那麼： <br>
$\underline{x}^tA\underline{x}=a_{11}x_1^2+a_{22}x_2^2+a_{33}x_3^2+2a_{12}x_1x_2\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;+2a_{13}x_1x_3+2a_{23}x_2x_3$

3. $x=\left(
\begin{array}{}
x_1\\
x_2\\
x_3
\end{array}
\right), \ A=\left(
\begin{array}{}
3 & 2 & 4\\
6 & 5 & 1\\
-2 & 5 & 8
\end{array}
\right)非對稱矩陣$，那麼：<br>
$\underline{x}^tA\underline{x}=3x_1^2+5x_2^2+8x_3^2\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;+2x_1x_2+4x_1x_3+6x_2x_1\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;+x_2x_3-2x_3x_1+5x_3x_2\\
\;\;\;\;\;\;\;\;\;\:=3x_1^2+5x_2^2+8x_3^2\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;+(2+6)x_1x_2+(4-2)x_1x_3\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;+(5+1)x_2x_3\\
\;\;\;\;\;\;\;\;\;\:=3x_1^2+5x_2^2+8x_3^2\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;+8x_1x_2+2x_1x_3+6z_2x_3$

4. 有式子 $3x_1^2-5x_2^2+7x_3^2+8x_1x_2+4x_1x_3-12x_2x_3$ 如果要將它改寫成 $\underline{x}^tA\underline{x}$ ($A$是對稱矩陣) 的話，試求 $A=\left(
\begin{array}{}
a_{11} & a_{12} & a_{13}\\
a_{22} & a_{22} & a_{23}\\
a_{33} & a_{32} & a_{33}
\end{array}
\right)=\left(
\begin{array}{}
a_{11} & a_{12} & a_{13}\\
a_{12} & a_{22} & a_{23}\\
a_{13} & a_{23} & a_{33}
\end{array}
\right)$ 的各個成分。<br>
$A$ 的對角成分：$a_{11},a_{22},a_{33}$ 分別是 $x_1^2,x_2^2,x_3^2$ 的系數： $3,-5,7$。非對角成分 $a_{12}(=a_{21})$ 等於 $x_1x_2$ 系數的一半：$4$，$a_{13}(=a_{31})$ 等於 $x_1x_3$ 系數的一半:$2$,
$a_23(=a_{32})$ 等於 $x_2x_3$ 系數的一半：$-6$。<br>
$\therefore A=\left(
\begin{array}{}
3 & 4 & 2\\
4 & -5 & -6\\
2 & -6 & 7
\end{array}
\right)$
